version: '3.3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8282:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: 
      --init-file /data/application/init.sql
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports: 
      - 6033:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - dbdata:/var/lib/mysql
  phpmydmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports: 
      - 8181:80
volumes:
  dbdata:
  # data:
  #   container_name: flask_data
  #   image: mysql:8.0
  #   volumes:
  #     - /var/lib/mysql
  #   command: "true"