version: '3'

networks:
    nginx-php74-mysql8-node-phpmyadmin:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - nginx-php74-mysql8-node-phpmyadmin

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9010:9010"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php74-mysql8-node-phpmyadmin

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "6033:3306"
        volumes:
            - ./init.sql:/data/application/init.sql
            - ./mysql:/var/lib/mysql
        command: 
            --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
            --init-file /data/application/init.sql
        restart: always 
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: coucou05
            MYSQL_PASSWORD: coucou05
        networks:
            - nginx-php74-mysql8-node-phpmyadmin

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php74-mysql8-node-phpmyadmin
    phpmydmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports: 
            - 8181:80
        networks:
            - nginx-php74-mysql8-node-phpmyadmin