<?php

namespace ContainerQvLoXXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Contact' shared autowired service.
     *
     * @return \App\Entity\Contact
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Contact.php';

        return $container->privates['App\\Entity\\Contact'] = new \App\Entity\Contact();
    }
}
