<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA3dvLWJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA3dvLWJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA3dvLWJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA3dvLWJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA3dvLWJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'A3dvLWJ',
    'container.build_id' => 'eba60b3b',
    'container.build_time' => 1600881541,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA3dvLWJ');
