<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVOgLOwr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVOgLOwr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVOgLOwr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVOgLOwr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVOgLOwr\App_KernelDevDebugContainer([
    'container.build_hash' => 'VOgLOwr',
    'container.build_id' => 'e9194a89',
    'container.build_time' => 1600415720,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVOgLOwr');
