<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container24RWPfV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container24RWPfV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container24RWPfV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container24RWPfV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container24RWPfV\App_KernelDevDebugContainer([
    'container.build_hash' => '24RWPfV',
    'container.build_id' => 'b31328a7',
    'container.build_time' => 1609946172,
], __DIR__.\DIRECTORY_SEPARATOR.'Container24RWPfV');
