<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
<<<<<<< HEAD
    'app_home' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/']], [], []],
    'app_contacts_show' => [['id'], ['_controller' => 'App\\Controller\\ContactController::show'], ['id' => '[0-9]+'], [['variable', '/', '[0-9]+', 'id', true], ['text', '/contacts']], [], []],
=======
    'home' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/']], [], []],
>>>>>>> emma
];
